//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HinttechPractice.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Holiday
    {
        public System.Guid HolidayId { get; set; }
        public System.Guid UserId { get; set; }
        public System.DateTime DateFrom { get; set; }
        public System.DateTime DateTo { get; set; }
        public string Description { get; set; }
    
        public virtual User User { get; set; }
    }
}
