//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HinttechPractice.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Holidays = new HashSet<Holiday>();
            this.VacationPeriods = new HashSet<VacationPeriod>();
        }
    
        public System.Guid UserId { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public string Firstname { get; set; }
        public string Lastname { get; set; }
        public string Email { get; set; }
        public bool IsUserRegistered { get; set; }
        public bool IsAdmin { get; set; }
        public byte[] ProfilePicture { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<System.DateTime> LastLoginDate { get; set; }
        public int VacationDays { get; set; }
    
        public virtual ICollection<Holiday> Holidays { get; set; }
        public virtual ICollection<VacationPeriod> VacationPeriods { get; set; }
    }
}
